name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Delphi environment
      uses: vsoft-dpk/setup-delphi@v2
      with:
        version: '11.3'  # Adjust to your Delphi version

    - name: Build project
      run: msbuild /t:Build /p:Configuration=Release ProjectGroup1.dproj

    - name: Run DUnitX tests
      run: Project2.exe
